### ISSUE TITLE
Repetition

### ISSUE THREAD

**Issue by Alessandro1984** [kamlage/R_HWR_public#1]
Dear Beate,

well done! I would only avoid to [define the variables every time](https://github.com/kamlage/R_HWR_public/blob/906e39543583b6bb03255fc29bcfbf86bac1cc19/09.05.2023_Homework_BK.R#LL17C9-L20C68) in the plot. It is a repetition, so it is more convenient if you define them only once before the plots.

Best wishes

Alessandro

**Comment by kamlage** [comment]
Dear Allessandro,

thank you. I added variable definition separately.

Best regards
Beate

**Comment by kamlage** [comment]
done
