### ISSUE TITLE
Save the data

### ISSUE THREAD

**Issue by Alessandro1984** [kamlage/R_HWR_public#2]
Dear Beate,

well done! In addition, once the graph is finished, you could [save the data locally](https://github.com/kamlage/R_HWR_public/blob/1af0dc415689fe6b6597a26e596e9ec4969c0918/23.05.2023_homework_BK.R#LL48C9-L48C9) to avoid pulling the data from dbnomics every time the full script is run.

Best wishes

Alessandro

**Comment by kamlage** [comment]
done

**Comment by kamlage** [comment]
code to save data locally added
