### ISSUE TITLE
Cross-referencing missing

### ISSUE THREAD

**Issue by Alessandro1984** [kamlage/R_HWR_public#6]
Dear @kamlage,

I have checked the homework from 13.06.2023. Well done! The only thing missing is [cross-referencing](https://bookdown.org/yihui/rmarkdown-cookbook/cross-ref.html) of table and figure in the document. Try including them by following the link above and the example in last week's file.

Best wishes

Alessandro

**Comment by kamlage** [comment]
> Dear @kamlage,
> 
> I have checked the homework from 13.06.2023. Well done! The only thing missing is [cross-referencing](https://bookdown.org/yihui/rmarkdown-cookbook/cross-ref.html) of table and figure in the document. Try including them by following the link above and the example in last week's file.
> 
> Best wishes
> 
> Alessandro

**Comment by kamlage** [comment]
Dear Alessandro,
thanks for proofreading. I added the cross-referencing of table and figure. 
See you next Tuesday
Best regards
Beate
